routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
    return view('welcome');
});
/*movies*/
Route::resource('movie','MovieController');
Route::get('movie/destroy/{id}',['as'=>'movie/destroy','uses'=>'MovieController@destroy']);
Route::post('movie/show',['as'=>'movie/show','uses'=>'Moviecontroller@show']);

/*categorias*/
Route::resource('category','categoryController');
Route::get('category/destroy/{id}',['as'=>'category/destroy','uses'=>'categoryController@destroy']);
Route::post('category/show',['as'=>'category/show','uses'=>'categorycontroller@show']);

/*usuarios*/
Route::resource('user','UserController');
Route::get('user/destroy/{id}',['as'=>'user/destroy','uses'=>'UserController@destroy']);
Route::post('user/show',['as'=>'user/show','uses'=>'Usercontroller@show']);
Auth::routes();

/*state*/
Route::resource('state','StateController');
Route::get('state/destroy/{id}',['as'=>'state/destroy','uses'=>'StateController@destroy']);
Route::post('state/show',['as'=>'state/show','uses'=>'Statecontroller@show']);
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/movies/list.blade.php
@extends('layouts.app')
@section('content')
  @include('navbar')

<section class="container">
    <div class="row">

        <article class="col-md-12">
            {!! Form::open(['route' => 'movie/show', 'method' => 'post', 'novalidate', 'class' => 'form-inline']) !!}
            <div class="form-group">
               
                <input type="text" name="name" class="form-control">
            </div>
            <div class="">
                <button type="submit" class="btn btn-default">Search</button>
                <a href="{{ route('movie.index') }}" class="btn btn-primary">All</a>
                <a href="{{ route('movie.create') }}" class="btn btn-primary">Create</a>
            </div>

            {!! Form::close() !!}
        </article>

        <article class="col-md-12">
        <table class="table table-condensed table-striped table-bordered">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>User</th>
                <th>State</th>
                 <th>Category</th>
                <th>Action</th>
            </tr>
        </thead>
            <tbody>
                @foreach($movies as $movie)
                <tr>
                    <td>{{ $movie->name }}</td>
                    <td>{{ $movie->description }}</td>
                     <td>{{ $movie->user->name }}</td>
                     <td>{{ $movie->state->state }}</td>
                    
                     

                    <td>
                        <a class="btn btn-primary btn-xs" href="{{ route('movie.edit',['id' => $movie->id])}}">Edit</a>
                        <a class="btn btn-danger btn-xs" href="{{ route('movie/destroy',['id' => $movie->id]) }}">Delete</a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        </article>
    </div>
</section>
@endsection

resources/views/movies/new.blade.php
@extends('Layouts.app')
@section('content')
@include('navbar')
<section class="container" >
    <div class="row">
        <article class="col-md-10 col-md-offset-1">
            {!!Form::open(['route'=>'movie.store','method'=>'post','novalidate'])!!}
            <div class="form-group" >
                <label>Nombre</label>
                <input type="text" name="name" class="form-control" required >
            </div>
            <div class="form-group">
                <label>Descripcion</label>
                <input type="text" name="description" class="form-control" required >
            </div>
            <div class="form-group">
                <label>Categorias</label>
                 
            </div>
            <div class="form-group">
            <select name="listCategories[]" class="form-control">
                <option value="">--Escoja la categoria</option>
                @foreach ($category as $categories)
                <option value="{{$categories->id}}">{{ $categories->name}}</option>
                @endforeach
            </select>
            
        </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success" > Enviar </button>
            </div>
            {!!Form::close() !!}
        </article>
    </div>
</section>
@endsection

resources/views/movies/update.blade.php
@extends('Layouts.app')
@section('content')
@include('navbar')
<section class="container" >
    <div class="row">
        <article class="col-md-10 col-md-offset-1">
            {!!Form::model($movie,['route'=>['movie.update',$movie->id],'method'=>'put','novalidate'])!!}
            <div class="form-group" >
                <label>Nombre</label>
                <input type="text" name="name" class="form-control" required value="{{$movie->name}}" >
            </div>
            <div class="form-group">
                <label>Descripcion</label>
                <input type="text" name="description" class="form-control" required value="{{$movie->description}}"  >
            </div>
            <div class="form-group">
                <label>Estado</label>
                <select name="state_id"class="form-control">
                <option value="">--Estado--</option>
                @foreach ($states as $state)
                <option value="{{$state->id}}">{{ $state->state}}</option>
                @endforeach
            </select>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success" > Enviar </button>
            </div>
            {!!Form::close() !!}
        </article>
    </div>
</section>
@endsection