routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
    return view('welcome');
});
/*movies*/
Route::resource('movie','MovieController');
Route::get('movie/destroy/{id}',['as'=>'movie/destroy','uses'=>'MovieController@destroy']);
Route::post('movie/show',['as'=>'movie/show','uses'=>'Moviecontroller@show']);

/*categorias*/
Route::resource('category','categoryController');
Route::get('category/destroy/{id}',['as'=>'category/destroy','uses'=>'categoryController@destroy']);
Route::post('category/show',['as'=>'category/show','uses'=>'categorycontroller@show']);

/*usuarios*/
Route::resource('user','UserController');
Route::get('user/destroy/{id}',['as'=>'user/destroy','uses'=>'UserController@destroy']);
Route::post('user/show',['as'=>'user/show','uses'=>'Usercontroller@show']);
Auth::routes();

/*state*/
Route::resource('state','StateController');
Route::get('state/destroy/{id}',['as'=>'state/destroy','uses'=>'StateController@destroy']);
Route::post('state/show',['as'=>'state/show','uses'=>'Statecontroller@show']);
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
   
    protected  $tabla='users';
    protected $fillable = ['name','email','password'];
    protected $guarded = ['id'];
    
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'state_id', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    public function movies(){
        return $this->hasMany('App\Models\Movie');
    }
    public function state(){
        return $this->belongsTo('App\Models\State');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User as User;

class UserController extends Controller
{
     public function store(Request $request)
    {
         $user = new User;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = $request->password;
        $user->state_id = 1;
        $user->save();
        return redirect('user');     
    }

    public function create()
    {
        return \View::make('users/new');
    }
    public function index()
    {
        $users = User::all();
        return \View::make('users/list',compact('users'));
    }

    public function edit($id) {
        $user = User::find($id);
        return \View::make('users/update', compact('user'));
    }

    public function update($id, Request $request) {
        $user = User::find($id);
        $user->name = $request->name;
        $user->email = $request->email;
         $user->password = $request->password;
        $user->save();
        return redirect('user');
    }

    public function show(Request $request) {
        $users = User::where('name', 'like', '%' . $request->name . '%')->get();
        return \View::make('users/list', compact('users'));
    }

    public function destroy($id) {
        $user = User::find($id);
        $user->delete();
        return redirect()->back();
    }
}

resources/views/users/list.blade.php
@extends('layouts.app')
@section('content')
@include('navbar')
<section class="container">
	<div class="row">
		<article class="col-md-12">
			{!! Form::open(['route' => 'user/show', 'method' => 'post', 'class' => 'form-inline']) !!}
			<div class="form-gorup">
 				<input type="text" class="form-control" name="name">
			</div>
			<div class="">
				<button type="submit" class="btn btn-default">Search</button>
				<a href="{{ route('user.index') }}" class="btn btn-primary">All</a>
                <a href="{{ route('user.create') }}" class="btn btn-primary">Create</a>
			</div>
			{!! Form::close() !!}
		</article>
		<article class="col-md-12">
			<table class="table table-condensed table-striped table-bordered">
				<thead>
					<tr>
						<th>Nombre</th>
						<th>Email</th>
						
						<th>Opciones</th>
					</tr>
				</thead>
				<tbody>
					@foreach($users as $user)
					<tr>
						<td>{{ $user->name}}</td>
						<td>{{ $user->email}}</td>
						
						
						<td>
							<a class="btn btn-primary btn-xs" href="{{ route('user.edit',['id' => $user->id]) }}">Edit</a>
							 <a class="btn btn-danger btn-xs" href="{{ route('user/destroy',['id' => $user->id]) }}">Delete</a>
						</td>
					</tr>
					@endforeach
				</tbody>
			</table>
			
		</article>
	</div>
</section>
@endsection

resources/views/users/new.blade.php
@extends('layouts.app')
@section('content')
@include('navbar')
<section class="container">
	<div class="row">
		<article class="col-md-10 col-md-offset-1">
		{!! Form::open(['route' => 'user.store', 'method' => 'post', 'novalidate']) !!}
		<div class="form-group">
			<label>Nombre</label>
			<input type="text" name="name" class="form-control" required>
        </div>
        <div class="form-group">
			<label>Emai</label>
			<input type="text" name="email" class="form-control" required>
        </div>
        <div class="form-group">
			<label>Password</label>
			<input type="text" name="password" class="form-control" required>
        </div>
        <div class="form-group">
			
			<button type="submit" class="btn btn-success">Enviar</button>
        </div>
        {!! Form::close() !!}
		 </article>
        
	</div>
</section>
@endsection

resources/views/users/update.blade.php
@extends('Layouts.app')
@section('content')
@include('navbar')
<section class="container" >
    <div class="row">
        <article class="col-md-10 col-md-offset-1">
            {!!Form::model($user,['route'=>['user.update',$user->id],'method'=>'put','novalidate'])!!}
            <div class="form-group" >
                <label>Nombre</label>
                <input type="text" name="name" class="form-control" required value="{{$user->name}}" >
            </div>
            <div class="form-group">
                <label>email</label>
                <input type="text" name="email" class="form-control" required value="{{$user->email}}"  >
            </div>
            <div class="form-group">
                <label>Password</label>
                <input type="text" name="password" class="form-control" required value="{{$user->password}}"  >
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success" > Enviar </button>
            </div>
            {!!Form::close() !!}
        </article>
    </div>
</section>
@endsection