routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
    return view('welcome');
});
/*movies*/
Route::resource('movie','MovieController');
Route::get('movie/destroy/{id}',['as'=>'movie/destroy','uses'=>'MovieController@destroy']);
Route::post('movie/show',['as'=>'movie/show','uses'=>'Moviecontroller@show']);

/*categorias*/
Route::resource('category','categoryController');
Route::get('category/destroy/{id}',['as'=>'category/destroy','uses'=>'categoryController@destroy']);
Route::post('category/show',['as'=>'category/show','uses'=>'categorycontroller@show']);

/*usuarios*/
Route::resource('user','UserController');
Route::get('user/destroy/{id}',['as'=>'user/destroy','uses'=>'UserController@destroy']);
Route::post('user/show',['as'=>'user/show','uses'=>'Usercontroller@show']);
Auth::routes();

/*state*/
Route::resource('state','StateController');
Route::get('state/destroy/{id}',['as'=>'state/destroy','uses'=>'StateController@destroy']);
Route::post('state/show',['as'=>'state/show','uses'=>'Statecontroller@show']);
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/State.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class State extends Model
{
   
    protected  $tabla='states';
    protected $fillable = ['state'];
    protected $guarded = ['id'];
    
    public function movies(){
    	return $this->hasMany('App\Models\Movie');
    }
    public function categories(){
    	return $this->hasMany('App\User');
    }
     public function users(){
    	return $this->hasMany('App\User');
    }
}

app/Http/Controllers/StateController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\State as State;

class StateController extends Controller
{
     public function store(Request $request)
    {
        $state = new State;
        $state->create($request->all());
        return redirect('state');   
    }

    public function create()
    {
        return \View::make('states/new');
    }
    public function index()
    {
        $states = State::all();
        return \View::make('states/list',compact('states'));
    }

    public function edit($id) {
        $state = State::find($id);
        return \View::make('states/update', compact('state'));
    }

    public function update($id, Request $request) {
        $state = State::find($id);
        $state->state = $request->state;
        
        $state->save();
        return redirect('state');
    }

    public function show(Request $request) {
        $states = State::where('state', 'like', '%' . $request->state . '%')->get();
        return \View::make('states/list', compact('states'));
    }

    public function destroy($id) {
        $state = State::find($id);
        $state->delete();
        return redirect()->back();
    }
}

resources/views/States/list.blade.php
@extends('layouts.app')
@section('content')
@include('navbar')
<section class="container">
	<div class="row">
		<article class="col-md-12">
			{!! Form::open(['route' => 'state/show', 'method' => 'post', 'class' => 'form-inline']) !!}
			<div class="form-gorup">
 				<input type="text" class="form-control" name="name">
			</div>
			<div class="">
				<button type="submit" class="btn btn-default">Search</button>
				<a href="{{ route('state.index') }}" class="btn btn-primary">All</a>
                <a href="{{ route('state.create') }}" class="btn btn-primary">Create</a>
			</div>
			{!! Form::close() !!}
		</article>
		<article class="col-md-12">
			<table class="table table-condensed table-striped table-bordered">
				<thead>
					<tr>
						<th>Estado</th>
						<th>Opciones</th>
					</tr>
				</thead>
				<tbody>
					@foreach($states as $state)
					<tr>
						<td>{{ $state->state}}</td>
						
						<td>
							<a class="btn btn-primary btn-xs" href="{{ route('state.edit',['id' => $state->id]) }}">Edit</a>
							 <a class="btn btn-danger btn-xs" href="{{ route('state/destroy',['id' => $state->id]) }}">Delete</a>
						</td>
					</tr>
					@endforeach
				</tbody>
			</table>
			
		</article>
	</div>
</section>
@endsection

resources/views/States/new.blade.php
@extends('layouts.app')
@section('content')
@include('navbar')
<section class="container">
	<div class="row">
		<article class="col-md-10 col-md-offset-1">
		{!! Form::open(['route' => 'state.store', 'method' => 'post', 'novalidate']) !!}
		<div class="form-group">
			<label>State</label>
			<input type="text" name="state" class="form-control" required>
        </div>
       
        <div class="form-group">
			
			<button type="submit" class="btn btn-success">Enviar</button>
        </div>
        {!! Form::close() !!}
		 </article>
        
	</div>
</section>
@endsection

resources/views/States/update.blade.php
@extends('Layouts.app')
@section('content')
@include('navbar')
<section class="container" >
    <div class="row">
        <article class="col-md-10 col-md-offset-1">
            {!!Form::model($state,['route'=>['state.update',$state->id],'method'=>'put','novalidate'])!!}
            <div class="form-group" >
                <label>Estado</label>
                <input type="text" name="state" class="form-control" required value="{{$state->name}}" >
            </div>
             
            <div class="form-group">
                <button type="submit" class="btn btn-success" > Enviar </button>
            </div>
            {!!Form::close() !!}
        </article>
    </div>
</section>
@endsection