routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
    return view('welcome');
});
/*movies*/
Route::resource('movie','MovieController');
Route::get('movie/destroy/{id}',['as'=>'movie/destroy','uses'=>'MovieController@destroy']);
Route::post('movie/show',['as'=>'movie/show','uses'=>'Moviecontroller@show']);

/*categorias*/
Route::resource('category','categoryController');
Route::get('category/destroy/{id}',['as'=>'category/destroy','uses'=>'categoryController@destroy']);
Route::post('category/show',['as'=>'category/show','uses'=>'categorycontroller@show']);

/*usuarios*/
Route::resource('user','UserController');
Route::get('user/destroy/{id}',['as'=>'user/destroy','uses'=>'UserController@destroy']);
Route::post('user/show',['as'=>'user/show','uses'=>'Usercontroller@show']);
Auth::routes();

/*state*/
Route::resource('state','StateController');
Route::get('state/destroy/{id}',['as'=>'state/destroy','uses'=>'StateController@destroy']);
Route::post('state/show',['as'=>'state/show','uses'=>'Statecontroller@show']);
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
       protected $table = 'categories';
    protected $fillable = ['name'];
    protected $guarded = ['id'];

    public function movies(){
    	return $this->belongsToMany('App\Models\Movie');
    }
    public function state(){
    	return $this->belongsTo('App\Models\State');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Category as Category;
use App\Models\State as State;

class categoryController extends Controller
{
	 public function store(Request $request)
    {
        $category = new Category;
        $category->name = $request->name;
        $category->state_id = 1;
        $category->save();
        return redirect('category');   
    }
    public function create()
    {
        return \View::make('categories/new');
    }
    public function index()
    {
        $categories = Category::all();
        return \View::make('categories/list',compact('categories'));
    }
    
     public function edit($id) {
        $category = Category::find($id);
        $states = State::all();
        return \View::make('categories/update', compact('category','states'));
    }

    public function update($id, Request $request) {
        $category = Category::find($id);
        $category->name = $request->name;
         $category->state_id =$request->state_id;
        $category->save();
        return redirect('category');
    }

    public function show(Request $request) {
        $categories = Category::where('name', 'like', '%' . $request->name . '%')->get();
        return \View::make('categories/list', compact('categories'));
    }

    public function destroy($id) {
        $category = Category::find($id);
        $category->delete();
        return redirect()->back();
    }
   
}

resources/views/categories/list.blade.php
@extends('layouts.app')
@section('content')
@include('navbar')
<section class="container">
	<div class="row">
		<article class="col-md-12">
			{!! Form::open(['route' => 'category/show', 'method' => 'post', 'class' => 'form-inline']) !!}
			<div class="form-gorup">
				 
				<input type="text" class="form-control" name="name">
			</div>
			<div class=" ">
				<button type="submit" class="btn btn-default">Search</button>
				<a href="{{ route('category.index') }}" class="btn btn-primary">All</a>
                <a href="{{ route('category.create') }}" class="btn btn-primary">Create</a>
			</div>
			{!! Form::close() !!}
		</article>
		<article class="col-md-12">
			<table class="table table-condensed table-striped table-bordered">
				<thead>
					<tr>
						<th>Nombre</th>
						<th>Estado</th>
						<th>Opciones</th>
						
					</tr>
				</thead>
				<tbody>
					@foreach($categories as $category)
					<tr>
						<td>{{ $category->name}}</td>
						<td>{{ $category->state->state}}</td>
						<td>
							<a class="btn btn-primary btn-xs" href="{{ route('category.edit',['id' => $category->id]) }}">Edit</a>
							 <a class="btn btn-danger btn-xs" href="{{ route('category/destroy',['id' => $category->id]) }}">Delete</a>
					@endforeach
				</tbody>
			</table>
			
		</article>
	</div>
</section>
@endsection

resources/views/categories/new.blade.php
@extends('layouts.app')
@section('content')
@include('navbar')
<section class="container">
	<div class="row">
		<article class="col-md-10 col-md-offset-1">
		{!! Form::open(['route' => 'category.store', 'method' => 'post', 'novalidate']) !!}
		<div class="form-group">
			<label>Categoria</label>
			<input type="text" name="name" class="form-control" required>
        </div>
       
        <div class="form-group">
			
			<button type="submit" class="btn btn-success">Enviar</button>
        </div>
        {!! Form::close() !!}
		 </article>
        
	</div>
</section>
@endsection

resources/views/categories/update.blade.php
@extends('Layouts.app')
@section('content')
@include('navbar')
<section class="container" >
    <div class="row">
        <article class="col-md-10 col-md-offset-1">
            {!!Form::model($category,['route'=>['category.update',$category->id],'method'=>'put','novalidate'])!!}
            <div class="form-group" >
                <label>name</label>
                <input type="text" name="name" class="form-control" required value="{{$category->name}}" >
            </div>
            <div class="form-group">
                <label>Estado</label>
                <select name="state_id"class="form-control">
                <option value="">--Estado--</option>
                @foreach ($states as $state)
                <option value="{{$state->id}}">{{ $state->state}}</option>
                @endforeach
            </select>
            </div>
            
            <div class="form-group">
                <button type="submit" class="btn btn-success" > Enviar </button>
            </div>
            {!!Form::close() !!}
        </article>
    </div>
</section>
@endsection